language: php
php:
    - 7.2
    - nightly
matrix:
    allow_failures:
        - php: nightly
before_script: composer install
script: phpunit --coverage-clover=coverage.clover
after_success:
     - bash <(curl -s https://codecov.io/bash)
